USE Merh_Univer

DROP TABLE TIMETABLE

CREATE TABLE TIMETABLE(
		IDGROUP INT CONSTRAINT TIMETABLE_GROUPS_FK FOREIGN KEY
							REFERENCES GROUPS(IDGROUP) NOT NULL,
		AUDITORIUM CHAR(30) CONSTRAINT TIMETABLE_AUDITORIUM_FK FOREIGN KEY
							REFERENCES AUDITORIUM(AUDITORIUM) NOT NULL,
		SUBJECT CHAR(10) CONSTRAINT TIMETABLE_SUBJECT_FK FOREIGN KEY
							REFERENCES SUBJECT(SUBJECT) NOT NULL,
		TEACHER NVARCHAR(10) CONSTRAINT TIMETABLE_TEACHER_FK FOREIGN KEY
							REFERENCES TEACHER(TEACHER) NOT NULL,
		WEEKDAY NVARCHAR(12) NOT NULL,
		LESSON INT
)


INSERT TIMETABLE (IDGROUP, AUDITORIUM, SUBJECT, TEACHER, WEEKDAY, LESSON)
VALUES (9, '408-2', 'ПМАПЛ', 'АРС', 'суббота', 3),
		(4, '324-1', 'ЛВ', 'ЗВГЦВ', 'четверг', 1),
		(10, '324-1', 'ПМАПЛ', 'АРС', 'суббота', 2)

		--свободные аудитории на день
SELECT A.AUDITORIUM as 'Свободные аудитории в сб'
FROM AUDITORIUM A
EXCEPT
(SELECT A.AUDITORIUM
FROM TIMETABLE T1, AUDITORIUM A
WHERE T1.WEEKDAY = 'суббота' AND A.AUDITORIUM = T1.AUDITORIUM);


--свободные аудитории на пару
SELECT A.AUDITORIUM as 'Свободные аудитории в сб 3 парой'
FROM AUDITORIUM A
EXCEPT
SELECT A.AUDITORIUM
FROM TIMETABLE T1, AUDITORIUM A
WHERE T1.WEEKDAY = 'суббота' AND T1.LESSON = 3 AND A.AUDITORIUM = T1.AUDITORIUM
;

INSERT TIMETABLE (IDGROUP, AUDITORIUM, SUBJECT, TEACHER, WEEKDAY, LESSON)
VALUES (5, '324-1', 'ЛВ', 'ЗВГЦВ', 'четверг', 3);


--окна у преподавателей
select distinct T.TEACHER_NAME as 'Преподаватель', T1.WEEKDAY as 'День недели', T1.LESSON as 'Занятая пара'
from TEACHER T, TIMETABLE T1, TIMETABLE T2
where T.TEACHER = T1.TEACHER and T1.WEEKDAY = T2.WEEKDAY and T1.LESSON != T2.LESSON
order by T.TEACHER_NAME asc, T1.WEEKDAY desc, T1.LESSON asc

select distinct T.TEACHER_NAME as 'Преподаватель', T1.WEEKDAY as 'День недели', T1.LESSON as '"окна"'
from TEACHER T, TIMETABLE T1, TIMETABLE T2
except 
	(select distinct T.TEACHER_NAME, T1.WEEKDAY, T1.LESSON
	from TEACHER T, TIMETABLE T1, TIMETABLE T2
	where T.TEACHER = T1.TEACHER and T1.WEEKDAY = T2.WEEKDAY and T1.LESSON != T2.LESSON)
order by T.TEACHER_NAME asc, T1.WEEKDAY desc, T1.LESSON asc

--окна у групп

select distinct GROUPS.IDGROUP as 'Группа', T1.WEEKDAY as 'День недели', T1.LESSON as 'Занятая пара'
from GROUPS, TIMETABLE T1, TIMETABLE T2
where GROUPS.IDGROUP = T1.IDGROUP and T1.WEEKDAY = T2.WEEKDAY and T1.LESSON != T2.LESSON
order by GROUPS.IDGROUP asc, T1.WEEKDAY desc, T1.LESSON asc
 
select distinct GROUPS.IDGROUP as 'Группа', T1.WEEKDAY as 'День недели', T1.LESSON as '"окна"'
from GROUPS, TIMETABLE T1, TIMETABLE T2
except
	(select distinct GROUPS.IDGROUP, T1.WEEKDAY, T1.LESSON
	from GROUPS, TIMETABLE T1, TIMETABLE T2
	where GROUPS.IDGROUP = T1.IDGROUP and T1.WEEKDAY = T2.WEEKDAY and T1.LESSON != T2.LESSON)
order by GROUPS.IDGROUP asc, T1.WEEKDAY desc, T1.LESSON asc