use Merh_Univer


------1
Select FACULTY.FACULTY_NAME,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME 
		from FACULTY,PULPIT,PROFESSION
		where FACULTY.FACULTY=PULPIT.FACULTY
		and PROFESSION.PROFESSION_NAME in
			(select PROFESSION_NAME from PROFESSION 
			where PROFESSION.PROFESSION_NAME like '%РЕУМНКНЦХЪ%' 
					or PROFESSION.PROFESSION_NAME like '%РЕУМНКНЦХХ%') 

-----2
Select FACULTY.FACULTY_NAME,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME 
		from FACULTY inner join PULPIT
		on FACULTY.FACULTY=PULPIT.FACULTY ,PROFESSION
		where PROFESSION.PROFESSION_NAME in
			(select PROFESSION_NAME from PROFESSION 
			where PROFESSION.PROFESSION_NAME like '%РЕУМНКНЦХЪ%' 
					or PROFESSION.PROFESSION_NAME like '%РЕУМНКНЦХХ%')

-----3
Select FACULTY.FACULTY_NAME,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME 
		from FACULTY inner join PULPIT 
		on FACULTY.FACULTY=PULPIT.FACULTY 
		inner join PROFESSION
		on FACULTY.FACULTY=PROFESSION.FACULTY
			where PROFESSION.PROFESSION_NAME like '%РЕУМНКНЦХ_%' 

-----4
select AUDITORIUM_NAME,AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
from AUDITORIUM as a
where AUDITORIUM_CAPACITY=(select top(1) AUDITORIUM_CAPACITY from AUDITORIUM as aa
						where a.AUDITORIUM_TYPE=aa.AUDITORIUM_TYPE
							order by AUDITORIUM_CAPACITY desc)

-----5
select distinct FACULTY_NAME
from FACULTY,PULPIT
where not exists (select * from PULPIT
					where PULPIT.FACULTY=FACULTY.FACULTY_NAME)


-----6
select top (1)
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'нюХо') [нюХо],
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'ад') [ад],
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'ясад') [ясад]
from PROGRESS

-----7
-- TASK 7 бяе юсдхрнпхх блеярхлнярэ йнрнпшу лемэье вел с кчани юсдхрнпхх рхою кй
SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY < ALL( SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
		WHERE AUDITORIUM_TYPE = 'кй' )
	ORDER BY AUDITORIUM_TYPE;


--  TASK 8 юсдхрнпхх бялеярхлнярэ йнрнпшу лемэье яюлни анкэьни юсдхрнпхх рхою кй
SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY < ANY( SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
		WHERE AUDITORIUM_TYPE = 'кй' )
	ORDER BY AUDITORIUM_TYPE;

------10
SELECT distinct A.BDAY,A.NAME,AA.NAME [NAME 2],AA.BDAY FROM STUDENT A, STUDENT AA
	WHERE DATEDIFF(month,  A.BDAY, AA.BDAY)=0 and DATEDIFF(day,  A.BDAY, AA.BDAY)=0  AND A.NAME!=AA.NAME


		select IDSTUDENT, IDGROUP, NAME, BDAY from STUDENT a
	where BDAY in ( select BDAY from STUDENT aa
		group by BDAY
		having count(BDAY)>=2)
		ORDER BY BDAY, NAME
