USE [Merh_Univer]
GO

/****** Object:  Table [dbo].[TIMETABLE]    Script Date: 12.05.2021 13:14:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIMETABLE](
	[IDGROUP] [int] NOT NULL,
	[AUDITORIUM] [char](30) NOT NULL,
	[SUBJECT] [char](10) NOT NULL,
	[TEACHER] [nvarchar](10) NOT NULL,
	[WEEKDAY] [nvarchar](12) NOT NULL,
	[LESSON] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TIMETABLE]  WITH CHECK ADD  CONSTRAINT [TIMETABLE_AUDITORIUM_FK] FOREIGN KEY([AUDITORIUM])
REFERENCES [dbo].[AUDITORIUM] ([AUDITORIUM])
GO

ALTER TABLE [dbo].[TIMETABLE] CHECK CONSTRAINT [TIMETABLE_AUDITORIUM_FK]
GO

ALTER TABLE [dbo].[TIMETABLE]  WITH CHECK ADD  CONSTRAINT [TIMETABLE_GROUPS_FK] FOREIGN KEY([IDGROUP])
REFERENCES [dbo].[GROUPS] ([IDGROUP])
GO

ALTER TABLE [dbo].[TIMETABLE] CHECK CONSTRAINT [TIMETABLE_GROUPS_FK]
GO

ALTER TABLE [dbo].[TIMETABLE]  WITH CHECK ADD  CONSTRAINT [TIMETABLE_SUBJECT_FK] FOREIGN KEY([SUBJECT])
REFERENCES [dbo].[SUBJECT] ([SUBJECT])
GO

ALTER TABLE [dbo].[TIMETABLE] CHECK CONSTRAINT [TIMETABLE_SUBJECT_FK]
GO

ALTER TABLE [dbo].[TIMETABLE]  WITH CHECK ADD  CONSTRAINT [TIMETABLE_TEACHER_FK] FOREIGN KEY([TEACHER])
REFERENCES [dbo].[TEACHER] ([TEACHER])
GO

ALTER TABLE [dbo].[TIMETABLE] CHECK CONSTRAINT [TIMETABLE_TEACHER_FK]
GO

